# Generated by Django 2.2 on 2019-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pole1',
            field=models.IntegerField(default=10),
        ),
    ]
