# Generated by Django 2.2 on 2019-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_pole1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='pole1',
        ),
    ]
